services:
  - type: web
    name: kjess-designs
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false

databases:
  - name: kjess-designs-db
    databaseName: kjessdesigns
    user: kjess_user
    plan: starter